List<String> imageList = [
  // 'assets/imp.png',
  // 'assets/teacher.png',
  // 'assets/img1.png',
  // 'assets/img2.png',
  // 'assets/img3.png',
  // 'assets/img5.png',
  // 'assets/image.png',
  'assets/College_premises.png',
  'assets/principal.png',
  'assets/freshers.png',
  'assets/member.png',
  'assets/teachers_day.png',
  'assets/graduation.png',
  'assets/sports.png',
  'assets/students.png',
];